/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Banking;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Akshay Kumar
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");
        setMinimumSize(new java.awt.Dimension(489, 410));
        getContentPane().setLayout(null);

        jLabel12.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("User Name");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 90, 90, 20);

        jTextField1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 80, 190, 30);

        jPasswordField1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(200, 130, 190, 30);

        jLabel13.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Old Password");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(70, 140, 100, 20);

        jLabel14.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("New Password");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(70, 190, 120, 20);

        jPasswordField2.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(200, 180, 190, 30);

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Change Password");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 30, 220, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 300, 90, 30);

        jLabel15.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Re-Type Password");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(70, 240, 120, 20);

        jPasswordField3.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jPasswordField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField3FocusLost(evt);
            }
        });
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(200, 230, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/deposit.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String user, pass, newpass;
    user=jTextField1.getText();
    pass=new String(jPasswordField1.getPassword());
    newpass=new String(jPasswordField2.getPassword());
    //First try statement starts to check destination account.
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/banking","root","password");
        Statement st=conn.createStatement();
        ResultSet set=st.executeQuery("Select * from user where User='"+user+"';");
        if(set.next())
        {
            String oldpass=set.getString("Password");
    
    if(pass.equals(oldpass))
    {
    //Making query
    String query="Update user set Password='"+newpass+"' where User='"+user+"';";
    
    int res=JOptionPane.showConfirmDialog(this, "Wanna change Password for sure?");
    if(res==JOptionPane.YES_OPTION)
    {
    //try statement to change Password.
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/banking","root","password");
        st=conn.createStatement();
            int rs=st.executeUpdate(query);
            if(rs==1)
                {
                    JOptionPane.showMessageDialog(this, "Password Changed Successfully.");
                }
                else
                    JOptionPane.showMessageDialog(this, "Something is wrong.");
            //Resetting form
            jTextField1.setText("");
            jPasswordField1.setText("");                    
            jPasswordField2.setText("");                    
            jPasswordField3.setText("");                    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
    }
    }
    //end of if statement.
    }
    else
        JOptionPane.showMessageDialog(this, "Password Invalid.");
        }
        else
            JOptionPane.showMessageDialog(this, "User Name does not exist.");
    //End of first try.
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField3FocusLost
    String pass, rtpass;
    pass=new String(jPasswordField2.getPassword());
    rtpass=new String(jPasswordField3.getPassword());
    if(pass.equals(rtpass)==false)
    {
        JOptionPane.showMessageDialog(this, "New Password and Re-type Password does not match.");
        jPasswordField3.setText("");
        jPasswordField2.requestFocus();
    }
    }//GEN-LAST:event_jPasswordField3FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
